update yml

diff --git a/.github/workflows/update_locales.yml b/.github/workflows/update_locales.yml
--- a/.github/workflows/update_locales.yml
+++ b/.github/workflows/update_locales.yml
@@ -1,14 +1,14 @@
 name: Fix locale issues
 
 on:
-  workflow_dispatch:
+  workflow_dispatch: # Allows manual trigger
   push:
     paths:
-      - '**.xml'
+      - '**/*.xml' # Changed to match any XML files
     branches:
       - master
 
-concurrency: 
+concurrency:
   group: "locale"
   cancel-in-progress: true
 
@@ -16,27 +16,32 @@ jobs:
   create:
     runs-on: ubuntu-latest
     steps:
-    - name: Generate access token
-      id: generate_token
-      uses: tibdex/github-app-token@v2
-      with:
-        app_id: ${{ secrets.GH_APP_ID }}
-        private_key: ${{ secrets.GH_APP_KEY }}
-        repository: "recloudstream/cloudstream"
-    - uses: actions/checkout@v4
-      with:
-        token: ${{ steps.generate_token.outputs.token }}
-    - name: Install dependencies
-      run: |
-        pip3 install lxml
-    - name: Edit files
-      run: |
-        python3 .github/locales.py
-    - name: Commit to the repo
-      run: |
-        git config --local user.email "111277985+recloudstream[bot]@users.noreply.github.com"
-        git config --local user.name "recloudstream[bot]"
-        git add .
-        # "echo" returns true so the build succeeds, even if no changed files
-        git commit -m 'chore(locales): fix locale issues' || echo
-        git push
+      - name: Generate access token
+        id: generate_token
+        uses: tibdex/github-app-token@v2
+        with:
+          app_id: ${{ secrets.GH_APP_ID }}
+          private_key: ${{ secrets.GH_APP_KEY }}
+          repository: "recloudstream/cloudstream"
+
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          token: ${{ steps.generate_token.outputs.token }}
+
+      - name: Install dependencies
+        run: |
+          pip3 install lxml
+
+      - name: Edit files
+        run: |
+          python3 .github/locales.py
+
+      - name: Commit changes to the repository
+        run: |
+          git config --local user.email "111277985+recloudstream[bot]@users.noreply.github.com"
+          git config --local user.name "recloudstream[bot]"
+          git add .
+          # Commit changes; if no changes, the command will not fail
+          git commit -m 'chore(locales): fix locale issues' || echo "No changes to commit"
+          git push
